### ISSUE TITLE
angular 12 : ng-alain-ms theme  ng server --configuration production  will cause error

### ISSUE THREAD

**Issue by ChangYinShung** [cipchk/ng-alain#2108]
### Reproduction link
[https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts)

### Steps to reproduce

1. The question is about  `ng-alain-ms` theme  
2. Download theme NG-Alain-Ms: 12.0.0   
3. npm i  
4. run with command  `ng serve --configuration production`  

### What is expected?
1. ng serve with params `--configuration production` should be work  at angular 12?
2. `ng build --configuration production` is  work fine.

### What is actually happening?
here is  error log  
``` txt
assets/color.less - Error: assets/color.less from Css Minimizer
D:\tt\ng-alain-ms\assets\color.less:2125:1: Unknown word
You tried to parse Less with the standard CSS parser; try again with the postcss-less parser [assets/color.less:2125,1]
You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
    at Input.error (D:\tt\ng-alain-ms\node_modules\postcss\lib\input.js:123:16)
    at Parser.unknownWord (D:\tt\ng-alain-ms\node_modules\postcss\lib\parser.js:518:22)
    at Parser.other (D:\tt\ng-alain-ms\node_modules\postcss\lib\parser.js:149:12)
    at Parser.parse (D:\tt\ng-alain-ms\node_modules\postcss\lib\parser.js:59:16)
    at parse (D:\tt\ng-alain-ms\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (D:\tt\ng-alain-ms\node_modules\postcss\lib\lazy-result.js:133:16)
    at Processor.process (D:\tt\ng-alain-ms\node_modules\postcss\lib\processor.js:36:12)
    at cssnanoMinify (D:\tt\ng-alain-ms\node_modules\css-minimizer-webpack-plugin\dist\utils.js:58:61)
    at minify (D:\tt\ng-alain-ms\node_modules\css-minimizer-webpack-plugin\dist\minify.js:15:32)
    at D:\tt\ng-alain-ms\node_modules\css-minimizer-webpack-plugin\dist\index.js:262:128
```

| Environment | Info |
|---|---|
| ng-alain | 12.2.3 |
| Browser | Can't open browser |

**Comment by ChangYinShung** [comment]
I move `color.less`  out of `assets folder ` and it work.
https://github.com/angular/angular-cli/issues/20812#issuecomment-844697524
