### ISSUE TITLE
angular版本12.2.13运行不了ng-alain

### ISSUE THREAD

**Issue by zhenzi0322** [cipchk/ng-alain#2155]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues/new/choose](https://github.com/ng-alain/ng-alain/issues/new/choose)

### Steps to reproduce
D:\works\angular\my-project>ng s
- Generating browser application bundles (phase: setup)...D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \""   invalidTarget.entryPoint.name   "\" has missing dependencies:\n"  
                ^

Error: The target entry-point "@delon/theme" has missing dependencies:
 - @angular/cdk/platform
 - @angular/cdk/bidi
 - @angular/cdk/overlay

    at TargetedEntryPointFinder.findEntryPoints (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)    at Object.mainNgcc (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

### What is expected?
D:\works\angular\my-project>ng s
- Generating browser application bundles (phase: setup)...D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \""   invalidTarget.entryPoint.name   "\" has missing dependencies:\n"  
                ^

Error: The target entry-point "@delon/theme" has missing dependencies:
 - @angular/cdk/platform
 - @angular/cdk/bidi
 - @angular/cdk/overlay

    at TargetedEntryPointFinder.findEntryPoints (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)    at Object.mainNgcc (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

### What is actually happening?
D:\works\angular\my-project>ng s
- Generating browser application bundles (phase: setup)...D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \""   invalidTarget.entryPoint.name   "\" has missing dependencies:\n"  
                ^

Error: The target entry-point "@delon/theme" has missing dependencies:
 - @angular/cdk/platform
 - @angular/cdk/bidi
 - @angular/cdk/overlay

    at TargetedEntryPointFinder.findEntryPoints (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)    at Object.mainNgcc (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (D:\works\angular\my-project\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ngcc_processor.js:175:16)
    at D:\works\angular\my-project\node_modules\@ngtools\webpack\src\ivy\host.js:146:18

| Environment | Info |
|---|---|
| ng-alain | 12.4.2 |
| Browser | 无 |

**Comment by devcui** [comment]
npm install @angular/cdk

**Comment by zhenzi0322** [comment]
> npm install @angular/cdk

Thank you

**Comment by cipchk** [comment]
@devcui @zhenzi0322 如果可以尽可能使用 `yarn` 来安装，`npm` 已经无药可救了。
