### ISSUE TITLE
JWTInterceptor 拦截器 请求报错

### ISSUE THREAD

**Issue by ttnkh21** [cipchk/ng-alain#2293]
### Reproduction link
[https://github.com/ng-alain/delon/blob/b1bc5372a5a52e6e1285c897abe4aa48b146cc86/packages/auth/src/token/jwt/jwt.interceptor.ts](https://github.com/ng-alain/delon/blob/b1bc5372a5a52e6e1285c897abe4aa48b146cc86/packages/auth/src/token/jwt/jwt.interceptor.ts)

### Steps to reproduce
设置拦截器为 JWTTokenModel 请求会报错 TypeError: this.interceptor.intercept is not a function

### What is expected?
设置拦截器为 JWTTokenModel 请求会报错 TypeError: this.interceptor.intercept is not a function

### What is actually happening?
设置拦截器为 JWTTokenModel 请求会报错 
core.mjs:7643 ERROR TypeError: this.interceptor.intercept is not a function
    at HttpInterceptorHandler.handle (http.mjs:1442:33)
    at HttpXsrfInterceptor.intercept (http.mjs:2055:21)
    at HttpInterceptorHandler.handle (http.mjs:1442:33)
    at HttpInterceptingHandler.handle (http.mjs:2094:27)
    at http.mjs:1269:70
    at doInnerSub (mergeInternals.js:19:19)
    at outerNext (mergeInternals.js:14:57)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at Observable._subscribe (innerFrom.js:51:24)

| Environment | Info |
|---|---|
| ng-alain | 14.0.0 |
| Browser | 谷歌最新 |

**Comment by cipchk** [comment]
@ttnkh21 麻烦提供一下重现步骤，我这里一切正常。

**Comment by ttnkh21** [comment]
解决了，可以关闭了，谢谢
